### ISSUE TITLE
'format-json' still needed?

### ISSUE THREAD

**Issue by Shaunm44** [codeforamerica/brigade-information#112]
Is this line from the readme still accurate?

> Before committing your change, please make sure that there are no formatting issues by running the bin/format-json script. (You will need to brew install jq moreutils for that script to run.)

I ran the exec, but the format of whitespace was shifted for the whole doc.

**Comment by tdooner** [comment]
Hm, interesting. What changes specifically are you seeing? And, what version of jq do you have? (`jq --version`)

**Comment by Shaunm44** [comment]
jq-1.6

**Comment by Shaunm44** [comment]
I'm going to close this issue.
The formatting issue was due to VSCode configs. 'format-json' works as described.
My issue was between keyboard and chair 🙃
