### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by thomasgroch** [codeforamerica/brigade-information#18]
I would like to know which fields are **mandatory** and which are **optional** for the registration of an organization in organizations.json.

**Comment by ondrae** [comment]
Good morning @ThomasGroch. The only mandatory field is the `name` attribute. If you want your groups to be included on the [Brigade map](http://www.codeforamerica.org/brigade/) or the [Code for All map](http://codeforall.org/) we'll need your `latitude` and `longitude` as well as a type of `Brigade` or `Code for All`. All the rest is extra, yet useful.

I'll add this info to the README.
