### ISSUE TITLE
How to model: Projects developed by few brigades, few repos per project

### ISSUE THREAD

**Issue by KrzysztofMadejski** [codeforamerica/brigade-information#7]
1. As Code for Poland coordinator I'm pushing for projects of one brigade to be reused by other, or even developed together. So we have the situation when one project will be mentioned in few brigades project lists.
   
   Will that situation be handled correctly by CfApi? 
2. Other scenario that I'm not sure how to model is that many projects have few github repos (ie. backend server, iOS mobile, Android mobile). From [docs](https://github.com/codeforamerica/brigade-information#projects-list) I understand that only one repo can be specified per project.

_Waiting for this issue with implementing project-list-export on our site https://github.com/epforgpl/web-kodujdlapolski.pl/issues/10_

**Comment by ondrae** [comment]
Hi @KrzysztofMadejski 
1. Many different Brigades can share a project, thats okay. It will appear many different times. See http://www.codeforamerica.org/brigade/projects?q=grano for example.
2. Just include all the repos. It will be a little messy, but you can come up with ways to then see all of them at once. Perhaps using the search like http://www.codeforamerica.org/brigade/projects?q=bizfriendly which has separate backend and frontend repos.

**Comment by KrzysztofMadejski** [comment]
Thank you, that clarifies all my questions.

**Comment by KrzysztofMadejski** [comment]
PS. @ondrae How does your script check if project file is in csv or json? File extension or mimetype is enough?

**Comment by KrzysztofMadejski** [comment]
Another thing. As per README.md "The projects list URL can also be a JSON file, with a list of strings containing GitHub project URLs."

But for example http://projects.betanyc.us/projects doesn't follow this pattern.

**Comment by ondrae** [comment]
There is only one group that uses a .json list. [Chi Hack Night](http://chihacknight.org/open-source-projects.html), the longest running civic hack night, uses [this list](https://raw.github.com/open-city/civic-json-files/master/projects.json) for their own website.

They are older than Code for America so I wanted to support them.
